#  #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: iarefeva <iarefeva@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/05/26 18:26:56 by iarefeva          #+#    #+#              #
#    Updated: 2024/05/29 13:30:50 by iarefeva         ###   ########.fr        #
#                                                                              #
#  #

NAME = libft.a

OBJ_PATH = ./obj/

CC = gcc
CFLAGS = -Wall -Wextra -Werror
INCLUDES = -I./

SRCS = 	ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c ft_atoi.c\
	ft_toupper.c ft_tolower.c ft_strncmp.c ft_memcmp.c ft_strlen.c ft_strlcpy.c\
	ft_strlcat.c ft_bzero.c ft_striteri.c ft_putchar_fd.c ft_putendl_fd.c ft_putstr_fd.c\
	ft_putnbr_fd.c ft_lstnew.c ft_memset.c ft_memcpy.c ft_memmove.c ft_calloc.c ft_memchr.c\
	ft_strchr.c ft_strrchr.c ft_strnstr.c ft_strdup.c ft_substr.c ft_strjoin.c ft_strtrim.c\
	ft_split.c ft_itoa.c ft_strmapi.c

OBJS = $(addprefix $(OBJ_PATH), $(SRCS:.c=.o))

BONUS_SRCS =	ft_lstnew.c ft_lstadd_front.c ft_lstsize.c\
 ft_lstlast.c ft_lstadd_back.c ft_lstdelone.c ft_lstclear.c\
 ft_lstiter.c ft_lstmap.c

BONUS_OBJS = $(addprefix $(OBJ_PATH), $(BONUS_SRCS:.c=.o))

all :	$(NAME)

# Objects directory rule
$(OBJ_PATH):
	mkdir -p $(OBJ_PATH)

$(OBJ_PATH)%.o: %.c | $(OBJ_PATH)
	$(CC) $(INCLUDES) $(CFLAGS) -c $< -o $@

$(NAME) : $(OBJS)
	@ar -rcs $(NAME) $(OBJS)

clean :
	@rm -rf $(OBJ_PATH)

fclean :	clean
	@rm -f $(NAME)

re :	fclean	all

bonus:	$(OBJS) $(BONUS_OBJS)
	@ar -rcs $(NAME) $(BONUS_OBJS)

.PHONY: all clean fclean re bonus
